### ISSUE TITLE
parser.description not included for sub-commands

### ISSUE THREAD

**Issue by rth** [gaborbernat/sphinx-argparse-cli#8]
While generating sphinx documentation for a CLI commands with subcommands, the description seems to be correctly rendered for the main command but not subcommands.

For example, with https://github.com/pyodide/pyodide/pull/1471 (sorry it's kind of hard to come up with minimal reproducible examples with sphinx), the description for the mkpkg subcommand is defined [here](https://github.com/pyodide/pyodide/blob/1574d3dc1abf12dbe5fdbf2c4492958634b92e62/pyodide_build/mkpkg.py#L120) it is correctly displayed when that command is called with `--help` argument. However it does not show in [the rendered documentation](https://pyodide--1471.org.readthedocs.build/en/1471/usage/api/pyodide-build-cli.html#pyodide-mkpkg) 

As far as I understand it would be processed in https://github.com/gaborbernat/sphinx-argparse-cli/blob/d5a74f6a1031689dae847eff7220b8951374af89/src/sphinx_argparse_cli/_logic.py#L131-L132 so not sure why it wouldn't be taken into account.

**Comment by gaborbernat** [comment]
The problem here is that currently, we use the content of the `help` message as a description for a subcommand. This is the description that you'll see when you call help without the subcommand present; think of:

```
git --help

   clone             Clone a repository into a new directory (from help)
   init              Create an empty Git repository or reinitialize an existing one
```

However, when you call the help on a sub command itself the help is not displayed and instead, the description argument governs the content showing up:

```
git clone --help

Clone a repository into a magical new directory (from description)
```

On reflection perhaps it's best to only use the help if the description is not set 🤔

**Comment by gaborbernat** [comment]
Resolved by https://github.com/gaborbernat/sphinx-argparse-cli/commit/17c6a96425d69b599479910f8b999acaa85694ba

**Comment by gaborbernat** [comment]
Released via https://github.com/gaborbernat/sphinx-argparse-cli/releases/tag/1.5.2
